name: miltiple jobs
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: Get code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run demo test
        run: |
          mvn clean test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:

      - name: Get code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: deploy code to server
        run: |
          echo "Deploying!!"
